catalogos/urls.py
from django.urls import path
from catalogos.views import CategoriaView, ProcesosPlantaView, CategoriaNew, CategoriaEdit, CategoriaDel,\
categoria_print, ProcesosPlantaNew, ProcesosPlantaEdit, ProcesosPlantaDel, OperacionDiariaView,\
OperacionDiariaNew, OperacionDiariaEdit, OperacionDiariaDel, ControlSulfatoView,\
ControlSulfatoNew, ControlSulfatoEdit, ControlSulfatoDel

urlpatterns = [
    path('categorias', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new' ),
    path('categoria/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categoria/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_delete'),
   
    path('ProcesosPlanta', ProcesosPlantaView.as_view(), name='ProcesosPlanta_list'),
    path('ProcesosPlanta/new', ProcesosPlantaNew.as_view(), name='ProcesosPlanta_new'),
    path('ProcesosPlanta/edit/<int:pk>', ProcesosPlantaEdit.as_view(), name='ProcesosPlanta_edit'),
    path('ProcesosPlanta/delete/<int:pk>', ProcesosPlantaDel.as_view(), name='ProcesosPlanta_delete'),
   

    path('OperacionDiaria', OperacionDiariaView.as_view(), name='OperacionDiaria_list'),
    path('OperacionDiaria/new', OperacionDiariaNew.as_view(), name='OperacionDiaria_new' ),
    path('OperacionDiaria/edit/<int:pk>', OperacionDiariaEdit.as_view(), name='OperacionDiaria_edit'),
    path('OperacionDiaria/delete/<int:pk>', OperacionDiariaDel.as_view(), name='OperacionDiaria_delete'),

    path('ControlSulfato', ControlSulfatoView.as_view(), name='ControlSulfato_list'),
    path('ControlSulfato/new', ControlSulfatoNew.as_view(), name='ControlSulfato_new' ),
    path('ControlSulfato/edit/<int:pk>', ControlSulfatoEdit.as_view(), name='ControlSulfato_edit'),
    path('ControlSulfato/delete/<int:pk>', ControlSulfatoDel.as_view(), name='ControlSulfato_delete'),





    path('categoria/print',categoria_print, name='categoria_print'),
    path('categoria/print/<int:pk>',categoria_print, name='categoria_print_one'),
    


]

cursodj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include(('generales.urls','generales'), namespace='generales')),
    path('catalogos/',include(('catalogos.urls','catalogos'), namespace='catalogos')),
    path('admin/', admin.site.urls),
]

catalogos/forms.py
#35
from django import forms

from catalogos.models import Categoria, ProcesosPlanta, OperacionDiaria, ControlSulfato


class CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        fields = ['descripcion','cruda','tratada','hr_servidas',
                'hr_sin_servicio', 'ag_cruda_recibida','ag_tratada_despachada',
                'consumo_sulfato','consumo_cloro', 'activo']
        labels= {'descripcion': "Descripción de la Categoría",
                "activo:":"Estado"}
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class ProcesosPlantaForm(forms.ModelForm):
    class Meta:
        model=ProcesosPlanta
        fields =['nombre',
                'hora',
                'temperatura_ag_cruda',
                'ph_ag_cruda',
                'color_ag_cruda',
                'turbiedad_ag_cruda',
                'color_sal_sedimentadores',
                'turbiedad_sal_sedimentadores',
                'cloro_res_sal_sedimentadores',
                'ph_sal_tq_desinfeccion',
                'turbiedad_sal_tq_desinfeccion',
                'temperatura_sal_tq_distribucion',
                'ph_sal_tq_distribucion',
                'color_sal_tq_distribucion',
                'turbiedad_sal_tq_distribucion',
                'alcalinidad_sal_tq_distribucion',
                'cloro_res_sal_tq_distribucion']

        labels= {'nombre': "Nombre funcionario",
                "activo:":"Estado"}

        widget={'nombre': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

#+++ OPERACIONES DIARIAS ++++++
class OperacionDiariaForm(forms.ModelForm):
    class Meta:
        model=OperacionDiaria
        fields =['nombre',
                'hora',
                'caudal_entrada_LxS',
                #'caudal_entrada_m3',
                'caudal_salida_LxS',
                #'caudal_salida_m3',
                'sul_dial',
               # 'sul_g_minut',
               # 'sul_mg_l',
                'precloracion_Lxdia',
                'cloracion_Lxdia',
               # 'cloracion_mg_l',
                'tq_almacenam_altura_m',
               # 'tq_almacenam_altura_m3',
                #'volumen_salida_acum',
                #'volumen_salida_real'
                ]
   

        labels= {'nombre': "Nombre funcionario",
                "activo:":"Estado"}

        widget={'nombre': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

#+++++++++++++++++++++++++++++++++++++++++++++++++++
class ControlSulfatoForm(forms.ModelForm):
    class Meta:
        model=ControlSulfato
        fields =[   'nombre',
                    'turno',
                    'consumo_sulf',
                    'sedimentador_1',
                    'sedimentador_2',
                    'existencia_bultos_sulf',
                    'consumo_cal',
                    'observaciones',
                    'alimenta_existencias',
]
        labels= {'nombre': "Nombre funcionario",
                        "activo:":"Estado"}


        widget={'nombre': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

catalogos/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from catalogos.models import Categoria, ProcesosPlanta, OperacionDiaria, ControlSulfato
from catalogos.forms import CategoriaForm, ProcesosPlantaForm, OperacionDiariaForm, ControlSulfatoForm
from generales.views import SinPrivilegios


class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "catalogos/categoria_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'


class CategoriaNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                   generic.CreateView):
    permission_required = "catalogos.add_categoria"
    model=Categoria
    template_name="catalogos/categoria_form.html"
    context_object_name = 'obj'
    form_class=CategoriaForm
    success_url= reverse_lazy("catalogos:categoria_list")
    success_message="Control Diario ingresado Satisfactoriamente"
#----Retorne Usuario-----
    def form_valid(self, form):
        form.instance.creadopor =self.request.user
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_categoria"
    model=Categoria
    template_name="catalogos/categoria_form.html"
    context_object_name = 'obj'
    form_class=CategoriaForm
    success_url= reverse_lazy("catalogos:categoria_list")
    success_message="El Control Diario se han ingresado Satisfactoriamente"


class CategoriaDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_categoria"
    model=Categoria
    template_name="catalogos/catalogos_del.html"
    context_object_name = 'obj'
    success_url= reverse_lazy("catalogos:categoria_list")

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

class ProcesosPlantaView(LoginRequiredMixin, generic.ListView):
    model = ProcesosPlanta
    template_name = "catalogos/ProcesosPlanta_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'

class ProcesosPlantaNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                   generic.CreateView):
    permission_required = "catalogos.add_ProcesosPlanta"
    model=ProcesosPlanta
    template_name="catalogos/ProcesosPlanta_form.html"
    context_object_name = 'obj'
    form_class=ProcesosPlantaForm
    success_url= reverse_lazy("catalogos:ProcesosPlanta_list")
    success_message="Procesos de Planta han ingresado Satisfactoriamente"

class ProcesosPlantaEdit(LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_ProcesosPlanta"
    model=ProcesosPlanta
    template_name="catalogos/ProcesosPlanta_form.html"
    context_object_name = 'obj'
    form_class=CategoriaForm
    success_url= reverse_lazy("catalogos:ProcesosPlanta_list")
    success_message="El Proceso de Planta se ha Actualizado Satisfactoriamente"

class ProcesosPlantaDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_ProcesosPlanta"
    model=ProcesosPlanta
    template_name="catalogos/ProcesosPlanta_del.html"
    context_object_name = 'obj'
    success_url= reverse_lazy("catalogos:ProcesosPlanta_list")

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

class OperacionDiariaView(LoginRequiredMixin, generic.ListView):
    model = OperacionDiaria
    template_name = "catalogos/OperacionDiaria_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'

class OperacionDiariaNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                   generic.CreateView):
    permission_required = "catalogos.add_OperacionDiaria"
    model=OperacionDiaria
    template_name="catalogos/OperacionDiaria_form.html"
    context_object_name = 'obj'
    form_class=OperacionDiariaForm
    success_url= reverse_lazy("catalogos:OperacionDiaria_list")
    success_message="Operacion Diaria ingresada Satisfactoriamente"

class OperacionDiariaEdit(LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_OperacionDiaria"
    model=OperacionDiaria
    template_name="catalogos/OperacionDiaria_form.html"
    context_object_name = 'obj'
    form_class=OperacionDiariaForm
    success_url= reverse_lazy("catalogos:OperacionDiaria_list")
    success_message="La Operacion Diaria se han actualizado Satisfactoriamente"

class OperacionDiariaDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_OperacionDiaria"
    model=OperacionDiaria
    template_name="catalogos/OperacionDiaria_del.html"
    context_object_name = 'obj' 
    success_url= reverse_lazy("catalogos:OperacionDiaria_list")


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

class ControlSulfatoView(LoginRequiredMixin, generic.ListView):
    model = ControlSulfato
    template_name = "catalogos/ControlSulfato_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'

class ControlSulfatoNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                   generic.CreateView):
    permission_required = "catalogos.add_ControlSulfato"
    model=ControlSulfato
    template_name="catalogos/ControlSulfato_form.html"
    context_object_name = 'obj'
    form_class=ControlSulfatoForm
    success_url= reverse_lazy("catalogos:ControlSulfato_list")
    success_message="Control sulfato ingresado Satisfactoriamente"

class ControlSulfatoEdit(LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_ControlSulfato"
    model=ControlSulfato
    template_name="catalogos/ControlSulfato_form.html"
    context_object_name = 'obj'
    form_class=ControlSulfatoForm
    success_url= reverse_lazy("catalogos:ControlSulfato_list")
    success_message="El Control del Sulfato se han actualizado Satisfactoriamente"

class ControlSulfatoDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_OperacionDiaria"
    model=ControlSulfato
    template_name="catalogos/OperacionDiaria_del.html"
    context_object_name = 'obj' 
    success_url= reverse_lazy("catalogos:OperacionDiaria_list")







#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
def categoria_print(self, pk=None):
    import io
    from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.platypus import Table

    response = HttpResponse(content_type='application/pdf')
    buff = io.BytesIO()
    doc = SimpleDocTemplate(buff,
                            pagesize=landscape(letter),
                            rightMargin=40,
                            leftMargin=40,
                            topMargin=60,
                            bottomMargin=18,
                            )
    categorias = []
    styles = getSampleStyleSheet()
    header = Paragraph("Listado de Categorías", styles['Heading1'])
    categorias.append(header)
    headings = ('nombre', 'Ag Cruda', 'Creación')
    if not pk:
        todascategorias = [(p.descripcion, p.cruda,p.tratada, p.hr_servidas,
            p.hr_sin_servicio,p.ag_cruda_recibida,p.ag_tratada_despachada,
            p.consumo_sulfato,p.consumo_cloro , p.creado)
                           for p in Categoria.objects.all().order_by('pk')]
    else:
        todascategorias = [(p.descripcion, p.cruda,p.tratada, p.hr_servidas,
            p.hr_sin_servicio,p.ag_cruda_recibida,p.ag_tratada_despachada,
            p.consumo_sulfato,p.consumo_cloro , p.activo, p.creado)
                           for p in Categoria.objects.filter(id=pk)]
    
    t = Table([headings] + todascategorias)
    t.setStyle(TableStyle(
        [
            ('GRID', (0, 0), (3, -1), 1, colors.dodgerblue),
            ('LINEBELOW', (0, 0), (-1, 0), 2, colors.darkblue),
            ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue)
        ]
    ))

    categorias.append(t)
    doc.build(categorias)
    response.write(buff.getvalue())
    buff.close()
    return response

catalogos/templates/catalogos/ProcesosPlanta_del.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
        <div class="panel panel-default">
            <div class="panel-heading">
                   Eliminar
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                {% csrf_token %}
                <div class="alert alert-success">
                    ¿Eliminar {{ obj.descripcion }} ?
                </div>
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                <a href="{% url 'catalogos:ProcesosPlanta_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
            </div>
        </div>
    </form>
{% endblock contenido %}

catalogos/templates/catalogos/ProcesosPlanta_form.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
                Editar/Crear Control Procesos Planta
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
            <a href="{% url 'catalogos:ProcesosPlanta_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
        </div>
    </div>
</form>
{% endblock contenido %}

catalogos/templates/catalogos/ProcesosPlanta_list.html
{% extends 'base/base.html' %}

{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{% url 'catalogos:ProcesosPlanta_new' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span> Nueva</a>
        <a href="{% url 'catalogos:categoria_print' %}" class="btn btn-warning" target="print"><span class="fa fa-print"></span> Imprimir</a>
    </div>
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables1">
            <thead>
              
                <tr>
                        <tr>
      

                    <th>Id</th>
                    <th>Operador</th>
                    <th>hora</th>
                    <th>temperatura_ag_cruda</th>
                    <th>ph_ag_cruda</th>
                    <th>color_ag_cruda</th>
                    <th>turbiedad_ag_cruda</th>
                    <th>color_sal_sedimentadores</th>
                    <th>turbiedad_sal_sedimentadores</th>
                    <th>cloro_res_sal_sedimentadores</th>
                    <th>ph_sal_tq_desinfeccion</th>
                    <th>turbiedad_sal_tq_desinfeccion</th>
                    <th>temperatura_sal_tq_distribucion</th>
                    <th>ph_sal_tq_distribucion</th>
                    <th>color_sal_tq_distribucion</th>
                    <th>turbiedad_sal_tq_distribucion</th>
                    <th>alcalinidad_sal_tq_distribucion</th>
                    <th>cloro_res_sal_tq_distribucion</th>

                    <th>Estado</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th>Acciones</th>


                        </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>

                    <td>{{ item.id }}</td>
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.hora}}</td>
                    <td>{{ item.temperatura_ag_cruda}}</td>
                    <td>{{ item.ph_ag_cruda}}</td>
                    <td>{{ item.color_ag_cruda}}</td>
                    <td>{{ item.turbiedad_ag_cruda}}</td>
                    <td>{{ item.color_sal_sedimentadores}}</td>
                    <td>{{ item.turbiedad_sal_sedimentadores}}</td>
                    <td>{{ item.cloro_res_sal_sedimentadores}}</td>
                    <td>{{ item.ph_sal_tq_desinfeccion}}</td>
                    <td>{{ item.turbiedad_sal_tq_desinfeccion}}</td>
                    <td>{{ item.temperatura_sal_tq_distribucion}}</td>
                    <td>{{ item.ph_sal_tq_distribucion}}</td>
                    <td>{{ item.color_sal_tq_distribucion}}</td>
                    <td>{{ item.turbiedad_sal_tq_distribucion}}</td>
                    <td>{{ item.alcalinidad_sal_tq_distribucion}}</td>
                    <td>{{ item.cloro_res_sal_tq_distribucion}}</td>
                   

                    <td>{{ item.activo|yesno:"Activo,Inactivo"}}</td>
                    <td>{{ item.creado|date:'d/m/Y H:i' }}</td>
                    <td>{{ item.modificado|date:'d/m/Y H:i' }}</td>


                    <td>
                        <a href="{% url 'catalogos:ProcesosPlanta_edit' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span></a>
                        <a href="{% url 'catalogos:ProcesosPlanta_delete' item.id %}" class="btn btn-danger btn-circle"><span class="fa fa-trash"></span></a>
                            
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}

catalogos/templates/catalogos/catalogos_del.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
        <div class="panel panel-default">
            <div class="panel-heading">
                   Eliminar
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                {% csrf_token %}
                <div class="alert alert-success">
                    ¿Eliminar {{ obj.descripcion }} ?
                </div>
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                <a href="{% url 'catalogos:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
            </div>
        </div>
    </form>
{% endblock contenido %}

catalogos/templates/catalogos/categoria_form.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
                Editar/Crear Control Diario
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
            <a href="{% url 'catalogos:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
        </div>
    </div>
</form>
{% endblock contenido %}

catalogos/templates/catalogos/categoria_list.html
{% extends 'base/base.html' %}

{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{% url 'catalogos:categoria_new' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span> Nueva</a>
        <a href="{% url 'catalogos:categoria_print' %}" class="btn btn-warning" target="print"><span class="fa fa-print"></span> Imprimir</a>
    </div>
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables1">
            <thead>

                <!--<th colspan="2" scope="col"></th>
                <th colspan="2" scope="col">Caudal Promedio</th>
            -->
                
               
                <tr>
                      <tr>
                        <th>Id</th>
                        <th>Operador</th>
                        <th>Cruda</th>
                        <th>Tratada</th>
                        <th>H Servidas</th>
                        <th>Hr sin Servicio</th>
                        <th>Ag Cruda Recibida</th>
                        <th>Ag Cruda Despachada</th>
                        <th>Consumo de Sulfato</th>
                        <th>Consumo de Cloro</th>                

                       
                        <th>Estado</th>
                        <th>Creado</th>
                        <th>Modificado</th>
                        <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.cruda }}</td>
                    <td>{{ item.tratada }}</td>
                    <td>{{ item.hr_servidas }}</td>
                    <td>{{ item.hr_sin_servicio }}</td>
                    <td>{{ item.ag_cruda_recibida }}</td>
                    <td>{{ item.ag_tratada_despachada }}</td>
                    <td>{{ item.consumo_sulfato }}</td>
                    <td>{{ item.consumo_cloro }}</td>
                    

                    <!--td>{{ item.creadopor}}</td-->
                    <td>{{ item.activo|yesno:"Activo,Inactivo"}}</td>
                    <td>{{ item.creado|date:'d/m/Y H:i' }}</td>
                    <td>{{ item.modificado|date:'d/m/Y H:i' }}</td>
                    <td>
                         <a href="{% url 'catalogos:categoria_edit' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span></a>
                        <a href="{% url 'catalogos:categoria_delete' item.id %}" class="btn btn-danger btn-circle"><span class="fa fa-trash"></span></a>
                        
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}